### ISSUE TITLE
Meditation Complete Screen

### ISSUE THREAD

**Issue by watadarkstar** [heylinda/heylinda-app#6]
It should have a:
- Donate button
- Skip button
- Present the screen after the user finished the meditation

**Comment by kevinfaveri** [comment]
I would also suggest that the Meditation Completion* Screen is presented **after** the user finishes a meditation. Sorry if this was the idea. I just wanted to make this point because people would be more inclined to share or donate after a refreshing meditation. Having the donation button somewhere else through the app would be cool tho.

**Comment by watadarkstar** [comment]
Agreed! @kevinfaveri 😄
